# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0003_auto_20171105_1506'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
