# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0004_auto_20171105_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=1000)),
                ('iscorrect', models.IntegerField()),
            ],
            options={
                'db_table': 'answers',
                'managed': False,
            },
        ),
    ]
