# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'question'},
        ),
        migrations.AlterModelOptions(
            name='replies',
            options={'verbose_name_plural': 'replies'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name_plural': 'session'},
        ),
        migrations.AlterModelOptions(
            name='stdintxn',
            options={'verbose_name_plural': 'stdintxn'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'student'},
        ),
        migrations.AddField(
            model_name='question',
            name='difflevel',
            field=models.CharField(db_column='Difflevel', default='', max_length=15),
        ),
        migrations.AddField(
            model_name='question',
            name='diffnum',
            field=models.BigIntegerField(db_column='Diffnum', default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(db_column='topic', default='', max_length=20),
        ),
    ]
