# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0003_auto_20171112_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='replies',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name_plural': 'Session'},
        ),
        migrations.AlterModelOptions(
            name='stdintxn',
            options={'verbose_name_plural': 'Stdintxn'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
    ]
