# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0004_auto_20171112_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difflevel',
            field=models.CharField(db_column='DiffLevel', max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='diffnum',
            field=models.BigIntegerField(db_column='DiffNum'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(db_column='Topic', max_length=100),
        ),
    ]
