# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0005_auto_20171112_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItsQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'its_question',
            },
        ),
        migrations.CreateModel(
            name='ItsStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'its_student',
            },
        ),
        migrations.AlterModelOptions(
            name='answers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='replies',
            options={},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stdintxn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='question',
            name='difflevel',
            field=models.CharField(blank=True, db_column='Difflevel', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='diffnum',
            field=models.BigIntegerField(blank=True, db_column='Diffnum', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, db_column='Topic', max_length=100, null=True),
        ),
    ]
