# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0008_auto_20171123_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stdintxn',
            options={'managed': False},
        ),
    ]
