# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0009_auto_20171123_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stdintxn',
            options={},
        ),
    ]
