# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0010_auto_20171123_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdintxn',
            name='ansid',
            field=models.ForeignKey(db_column='Ansid', on_delete=django.db.models.deletion.DO_NOTHING, to='webapps.Answers'),
        ),
        migrations.AlterField(
            model_name='stdintxn',
            name='qnid',
            field=models.ForeignKey(db_column='Qnid', on_delete=django.db.models.deletion.DO_NOTHING, to='webapps.Question'),
        ),
        migrations.AlterField(
            model_name='stdintxn',
            name='sessid',
            field=models.ForeignKey(db_column='Sessid', on_delete=django.db.models.deletion.DO_NOTHING, to='webapps.Session'),
        ),
    ]
