# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0011_auto_20171123_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdintxn',
            name='qnid',
            field=models.ForeignKey(db_column='Qnid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='webapps.Question'),
        ),
    ]
