# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0012_auto_20171123_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='itsquestion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='itsstudent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='replies',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stdintxn',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
